name: Metrics
on:
  # Schedule updates (every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual trigger
  workflow_dispatch:
  # Update on push to main
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic options
          user: mgalen007
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Enable language plugin
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Enable other useful plugins
          plugin_lines: yes
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year